legacy_layout=0

toggle_hud=Shift_R+F12

position=bottom-left
background_alpha=0.1
font_size=20
font_size_secondary=14

text_outline=0
text_outline_color=
text_outline_thickness=0.5

custom_text=SUPER POTATO HUD
offset_x=1

horizontal

# gpu_list=0 # shows INTEL iGPU
gpu_list=1 # show NVIDIA dGPU

gpu_stats
gpu_temp

cpu_stats
cpu_temp

vram
ram

# resolution

frametime=0
frame_timing=1 # shows the graph

# wine
fps

fps_color_change
fps_color=FF0000,FFFF00,39F900
fps_value=30,57
# red below 30, yellow 30–57, green above 57

text_color=f7e1d4
gpu_color=ffac93
cpu_color=ffac93
vram_color=ffd4c3
ram_color=ffd4c3
frametime_color=ffdaaa
wine_color=ffac93
engine_color=ffac93
horizontal_separator_color=837267
fps_color=ff9b64,ffeee2,ffdb94
